### ISSUE TITLE
Dev Sprint 1 Progress Reports

### ISSUE THREAD

**Issue by CameronAuler** [CameronAuler/ENSM#41]
- [x] Meet with the Capstone instructor for as many progress reports as required for Dev Sprint 1.
   - [x] Discuss the progress that has been made since the last check-in.
   - [x] Discuss the tasks that will be completed by the next check-in.
   - [x] Discuss any other talking points that the instructor wishes to cover.

**Comment by Sguinther** [comment]
1. 9:30 AM January 30th FIRST SPRINT UPDATE
2. 9:30 AM February 6 REPORT MEETING
